---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list: erlang_one::default
  - name: version_wrapper
    run_list: version_wrapper::default
  - name: uri_wrapper
    run_list: uri_wrapper::default
